import assert from 'node:assert/strict';
import { calculateEstimate, whatsappLink } from '../src/lib/estimate';
const base = { area: 1000, tier: 'signature' as const, propertyType: 'Apartment' as const, addons: [] };
const result = calculateEstimate(base);
assert.equal(result.total, 3800000);
assert.equal(result.low, 3230000);
assert.equal(result.high, 4370000);
assert.equal(result.days.low, 90);
assert.equal(result.days.high, 140);
assert.deepEqual(result.milestones.map(m => m.percent), [10,30,35,20,5]);
assert.equal(result.milestones.reduce((sum, m) => sum + m.amount, 0), result.total);
assert.equal(calculateEstimate({...base, tier: 'essential'}).total, 2500000);
assert.equal(calculateEstimate({...base, tier: 'bespoke'}).total, 5200000);
assert.equal(calculateEstimate({...base, addons: ['civil', 'permissions']}).total, 4175000);
assert.equal(calculateEstimate({...base, addons: ['civil', 'civil']}).total, 4150000);
for (const area of [0,149,25001,NaN,Infinity]) assert.throws(() => calculateEstimate({...base, area}));
assert.equal(calculateEstimate({...base, area: 150}).base, 570000);
assert.equal(calculateEstimate({...base, area: 25000}).base, 95000000);
const fractional = calculateEstimate({...base, area: 1000.31, addons:['electrical']});
assert.equal(fractional.milestones.reduce((s,m) => s+m.amount,0), fractional.total);
const old = process.env.NEXT_PUBLIC_WHATSAPP_NUMBER;
delete process.env.NEXT_PUBLIC_WHATSAPP_NUMBER;
assert.equal(whatsappLink('hello'), null);
process.env.NEXT_PUBLIC_WHATSAPP_NUMBER = 'not-a-number';
assert.equal(whatsappLink('hello'), null);
process.env.NEXT_PUBLIC_WHATSAPP_NUMBER = '+919876543210';
assert.equal(whatsappLink('hello & world'), 'https://wa.me/919876543210?text=hello%20%26%20world');
if (old === undefined) delete process.env.NEXT_PUBLIC_WHATSAPP_NUMBER; else process.env.NEXT_PUBLIC_WHATSAPP_NUMBER = old;
console.log('Estimate tests passed.');
